import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'

import { MicrophoneIcon, SearchIcon, ViewGridIcon } from "@heroicons/react/solid"
import Footer from '../components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'


export default function Home() {
  // require('dotenv').config();


  const searchInputRef = useRef(null)

  const router = useRouter();

  const search = e => {
    e.preventDefault()
    const term = searchInputRef.current.value;
    if(!term) return

    router.push(`/search?term=${term}`);
  }
  return (
    <>
      <div className='flex flex-col items-center justify-center h-screen'>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
          <div className='flex space-x-4 items-center'>
            <p className='link'>About</p>
            <p className='link'>Store</p>
          </div>

          <div className='flex space-x-4 items-center '>
            <p className='link'>Gmail</p>
            <p className='link'>Images</p>
            <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer' />

            <Avatar url="https://lh3.googleusercontent.com/fife/AKsag4NJMSnBcmhxdQGJW48-lSXNGbA8zgj-X0AtpDGyPFUIGjdZO7bI25Y65crtLrHm0w6Dew9F5mJtjp9LrfFO4O8hMOB6nO6-eUQqKs81fh1pEW-dForfbosJyyDhO2RkSirM3GAMvX7-kCBcnglOGbc_wTK0WUzC0yAauLlhls6lVv_LWmrDPcscza26fXAebTTc-9Uu6ceKxdy8dl7qexTjtwbtCjsKKQPZ0ObQnweBbaszWxFTcyE6lgGXqATjqXgERlimlRGfEKncQmpQnxxQTXCIyoeEMx0WAsRD8pGKF1M1Uco_z2REzEmI3sit7NNXQy53CA18Nv3DRCdbGaog5sNfY1xXEKoS4hq-h6JTwEBJbeMibKb0-dQ7ae7mpmDtoEquK-tWm6_KZapaT2b76MVEkGnITIhGHiwf0rBivErWHE8JRNxK1xJBqfihKHSLtsuLAPg-bG0nFrUBHs7-rlYAMb9EG6J3HxOCCcWk0bRt0qNQwNnnChUKsB-FfGQWJrSWCTOq3G4iiC1rBaySwe9g4lgqZcpwHo-4qGUB6aRCptLiKtWsgVIkEElxg49hY9nt4twctCVIKtpib6-KLAEUbPLJazQBKuJJyMsMcwfg2xCpMjFF03xwpofKA-JkDpwgvmJwq95WPilkEex6_FQbtHxz7nsEe_xFiC0TYHW3I40YvpmJifh1ihnaM7LB8OKk0e2QqIOsCtOuGfy07VZI09UUazQq0O7lYOCjATb_mjUahdmCQ5Q5cggol-NTK5JMVvf6KZxVlPEIOKbRgzWXoEL0zcP17COu__bGQs4ow3Imw_dkRSnu5dVKnxD22ht88sXByPN4nxSSk8-aS0mf5iaN5F1YcAcYVEPp40dm_W5njtIk2qP_T1NFbp_fS8uO_iv4x-VIs_uu0Koa4sWzZ2jqxxf3Mu8cCJ-qTj2_n-Vn3HwYSRhYi-NbDxH9o-czbVQp-oRGJJiCGs92mo4DveiTXC0usieWmlbeQvkF-aHD4ohra-BJbUzi_RSA6nqyIewxfGxr63Sy5SIY5-PmIma5hkWoW-aC8zkDm9fVfYd7VoKCbmfiO7Cerrgpj17yVSLAb38Gg1zHoVDwDX29S7iMB1mJVnapqI0oLBVpUsTsEc4wz5YQpw0I-J2eF9cwV3zneH8hKmsZI8BAvfdYY2QYwdsKZiKYlShuQXNsjLRpy-QK0PS-FO0lbLE4lMeLDByTOkwONsTPxUe3U6C5nNyWvGoPH4KSJO8DFgv-l7eQxE2MeQY4jNtLJbBjvkuFArxxG6FRbNNwdVaz1R8pIEp4IsH4GKA4BDp3vYO5CG3RS_-av3caec7pTPJVIWxdZKZX6kQZDu_118cSJv1qD6s1_ZaXcLaneOb5ZNrksJygexXoKFaLrZfRJCHWjFn_PtJdtsmMk9iWQpwMAnkhe8eAatpqzNzNjROdF1nQzMJFQcxk2Kk=s64-c" />
          </div>
        </header>

        <form className='flex flex-col items-center mt-44 flex-grow w-4/5'>
          <Image
            src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
            height={100}
            width={300} />

          <div className='flex w-full mt-5 hover:shadow-lg 
        focus-within:shadow-lg max-w-md rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl'>
            <SearchIcon className='h-5 mr-3 text-gray-500 ' />
            <input ref={searchInputRef} type='text' className='focus:outline-none  flex-grow ' />
            <MicrophoneIcon className='h-5' />
          </div>

          <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 
        sm:space-y-0 sm:flex-row sm:space-x-4'>
            <button onClick={search} className='btn'>Google Search</button>
            <button onClick={search} className='btn'>I'm Feeling Lucky</button>
          </div>
        </form>

      </div>
        <Footer/>
    </>
  )
}
